[package]
name = "ctypst-base"
version = "0.1.0"  # 初始版本
entrypoint = "lib.typ" # 包的入口文件
authors = ["Xyber Nova <xyber-nova@outlook.com>"]
license = "LGPL-2.1"
description = "基础的 Typst 中文支持，提供字体配置等核心功能。"

repository = "https://github.com/ctypst/ctypst-base"
homepage = "https://github.com/ctypst/ctypst-base"
keywords = ["chinese", "font", "typst", "cjk", "中文", "字体"]
exclude = ["docs/", "tests/"]